matrix:
  allow_failures:
    - os: windows
os:
  - osx
  - linux
  - windows
language: node_js
node_js:
  - node
  - 10
  - 9
  - 8
cache: cargo
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      choco install rust && refreshenv
    else
      curl https://sh.rustup.rs -sSf > /tmp/rustup.sh && /
      sh /tmp/rustup.sh -y && /
      export PATH="$HOME/.cargo/bin:$PATH" && /
      source "$HOME/.cargo/env"
    fi
  # Install NPM packages
  - node -v
  - npm -v
  - npm install
  - yarn
script:
  - npm test
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then yarn upload-binary || exit 0; fi;